#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false

# ===============================
# = Mysql configurations
# ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: jeonguk

# ===============================
# = Redis configurations
# ===============================ß
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

# ===============================
# = JPA configurations
# ===============================
  jpa:
    database: MYSQL
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: none
    database-platform: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  
# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.jeonguk.web: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO